### ISSUE TITLE
Action to digitize drainage channel fails

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#507]
QGIS 3.4.9 Windows x64

Action to digitize drainage channel fails probably due to QGIS filtering of detail_geometry_geometry NULL values depending on the geometry type in the layer configuration.

`AttributeError: 'NoneType' object has no attribute 'getFeatures'`

QgsProject.instance().mapLayer('od_wastewater_structure')  returns None instead of qgsVectorLayer object.

**Comment by varrieta** [comment]
It works for me (qgep 1.3.0, qgis 3.4.).

**Comment by ponceta** [comment]
What you have on python qgis action is something like this?

```
from qgepplugin.gui import forms

import qgepplugin

feature = next( QgsProject.instance().mapLayer('od_wastewater_structure').getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "obj_id" %]' ) ) ) )
qgepplugin.gui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')
```

**Comment by m-kuhn** [comment]
@ponceta what's the name of your wastewater structure layer? Probably no longer 'od_wastewater_structure'?

**Comment by ponceta** [comment]
I've corrected it to od_wastewater_structure

**Comment by ponceta** [comment]
Even if I check it on another layer :
![image](https://user-images.githubusercontent.com/8614223/61534897-17bea400-aa31-11e9-9b29-7c48811ae924.png)

**Comment by m-kuhn** [comment]
Checking again, it refers to the layer id which has been manually set in the original project.
`QgsProject.instance().mapLayersByName('Couvercles')[0]` should work

**Comment by m-kuhn** [comment]
But I'm considering another approach using regex on the dataSourceUri or the table name to be able to develop more generic code (to be implemented upstream in QGIS if possible).

**Comment by ponceta** [comment]
It works for digitize detailled geometry :+1: 

![image](https://user-images.githubusercontent.com/8614223/61535132-c367f400-aa31-11e9-945f-1469e80b0597.png)

```
ws_lyr = QgsProject.instance().mapLayersByName('od_wastewater_structure')[0]
feature = next( ws_lyr.getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "obj_id" %]' ) ) ) )
ws_lyr.startEditing()
ws_lyr.selectByIds([feature.id()])
qgis.utils.iface.setActiveLayer(ws_lyr)
qgis.utils.iface.actionAddPart().trigger()
```

But not for channel since qgep_plugin uses the same method (as I imagine)

```
**Une erreur est survenue lors de l'exécution du code suivant:**
from qgepplugin.gui import forms 

import qgepplugin 

feature = next( QgsProject.instance().mapLayersByName('od_wastewater_structure')[0].getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( 'ch176dc9WS021068' ) ) ) ) 
qgepplugin.gui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')

Traceback (most recent call last):
  File "", line 6, in 
  File "C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\gui\forms.py", line 22, in digitizeDrainageChannel
    layer.startEditing()
AttributeError: 'NoneType' object has no attribute 'startEditing'
```

**Comment by m-kuhn** [comment]
There is no support for using manually added layers as of yet. All needs to be done based on the original layers from the QGEP project (which can be renamed).

There are 3 possibilities I see:

 - Finetune your project to make it work
 - Update the plugin code using python only to be independent from layer ids
 - Update the plugin code and the QGIS API to be independent from layer ids

Required time to implement increases from top to bottom. Quality of development also increases from top to bottom.

**Comment by ponceta** [comment]
Like I checked with @3nids we also face a type issue since there's a QGIS bug on geometry type :

![image](https://user-images.githubusercontent.com/8614223/61536061-09be5280-aa34-11e9-9de5-621f86757056.png)

If your layer is loaded in CurvePolygonZ (manually through project editing), the action will fail since QGIS doesn't recognize the NULL geometries entities.

**Comment by ponceta** [comment]
> It works for me (qgep 1.3.0, qgis 3.4.).

Which 3.4.X? On 3.4.11 it is broken but it worked in 3.4.6 as I remember.

**Comment by ponceta** [comment]
This is due to a "Feature" or change of behaviour of QGIS when loading a geometry layer (filtering entities without geometry in it)

![image](https://user-images.githubusercontent.com/8614223/64170624-e10de300-ce50-11e9-8654-eec7c1b35628.png)

**Comment by haubourg** [comment]
> > It works for me (qgep 1.3.0, qgis 3.4.).
> 
> Which 3.4.X? On 3.4.11 it is broken but it worked in 3.4.6 as I remember.

@ponceta I think you should better explicitly ping Valentina here. Depending on the notification options she has, she may not get your question. And for the sake of keeping a readable discussion, this is a good practice too :smiley:

**Comment by varrieta** [comment]
Did get it ;)

Just tested it, and it works with QGIS 3.4.11

**Comment by varrieta** [comment]
Here is the code

from qgepplugin.gui import forms

import qgepplugin

feature = next(QgsProject.instance().mapLayer('od_wastewater_structure').getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "obj_id" %]' ) ) ) )
qgepplugin.gui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')

**Comment by 3nids** [comment]
closing the former issue
followup in #523

**Comment by ponceta** [comment]
It was linked to the access to public.geometry_columns in my database

**Solved using:**
```
GRANT ALL ON TABLE public.geometry_columns TO postgres;	
GRANT SELECT ON TABLE public.geometry_columns TO PUBLIC;
```
