### ISSUE TITLE
Python error when using the plugin profile tool

### ISSUE THREAD

**Issue by rbovard** [QGEP/QGEP#753]
**Describe the bug**
Python error when using the plugin profile tool

**To Reproduce**
Exact steps to reproduce the behavior:
1. Activate profile tool in QGEP plugin
2. Click on start and end nodes
3. See error: `Python error: An error has occurred while executing Python code: See message log (Python Error) for more details.`

```
qgepplugin\qgepplugin.py", line 414, in onProfileChanged
self.plotWidget.setProfile(profile)
qgepplugin\gui\qgepplotsvgwidget.py", line 109, in setProfile
self.profileChanged.emit(profile.asJson())
qgepplugin\tools\qgepprofile.py", line 517, in asJson
[element.asDict() for element in list(self.elements.values())]
qgepplugin\tools\qgepprofile.py", line 517, in 
[element.asDict() for element in list(self.elements.values())]
qgepplugin\tools\qgepprofile.py", line 420, in asDict
"usageCurrent": self.usage_current,
AttributeError: 'QgepProfileSpecialStructureElement' object has no attribute 'usage_current'
```

**Expected behavior**
The profile is drawn.

**Desktop (please complete the following information):**
 - QGEP plugin version: 1.5.5
 - QGEP datamodel version: 1.5.4 (should it be the same as the plugin?)
 - QGEP project file version: 3.22.9
 - QGIS Version: 3.22.9
 - OS: Windows 10

**Additional context**
When clickin on unrelated nodes, there is this message `No path found`, which is correct I think?

**Comment by sjib** [comment]
@rbovard Is the behavior onliy in QGIS 3.22.x. ?
Does it work in 3.16?

Datamodel you should use the latest version https://github.com/QGEP/datamodel/releases (or at least check on the changes after if they could influence this behavior)

**Comment by rbovard** [comment]
Thanks for your answer @sjib 

I've updated to the latest version of datamodel 1.5.6-1 and the Python error doesn't occur again, sorry for the noise.
