### ISSUE TITLE
Error when digitizing drainaige channel

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#490]
I've corrected my python actions according to : https://github.com/QGEP/QGEP/pull/483

```
from qgepplugin.gui import forms

import qgepplugin

feature = next( QgsProject.instance().mapLayer('od_wastewater_structure').getFeatures( QgsFeatureRequest().setFilterExpression( 'obj_id = \'{}\''.format( '[% "obj_id" %]' ) ) ) )
qgepplugin.gui.forms.digitizeDrainageChannel(feature.id(), 'od_wastewater_structure')
```

Updated QGEP plugin to 1.1.9

Get following errors :

```
2019-04-18T14:58:28     WARNING    Traceback (most recent call last):
              File "C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptooladdfeature.py", line 456, in canvasReleaseEvent
              self.geometry = QgsGeometry.fromPolygon([[pt1, pt2, pt3, pt4, pt1]])
             AttributeError: type object 'QgsGeometry' has no attribute 'fromPolygon'
             
2019-04-18T14:58:35     WARNING    Traceback (most recent call last):
              File "C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptooladdfeature.py", line 456, in canvasReleaseEvent
              self.geometry = QgsGeometry.fromPolygon([[pt1, pt2, pt3, pt4, pt1]])
             AttributeError: type object 'QgsGeometry' has no attribute 'fromPolygon'
             
2019-04-18T14:58:36     WARNING    Traceback (most recent call last):
              File "C:/Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\tools\qgepmaptooladdfeature.py", line 456, in canvasReleaseEvent
              self.geometry = QgsGeometry.fromPolygon([[pt1, pt2, pt3, pt4, pt1]])
             AttributeError: type object 'QgsGeometry' has no attribute 'fromPolygon'
             
2019-04-18T14:58:37     WARNING    RecursionError: maximum recursion depth exceeded
```

Digitizing detailled wastewater structure works fine.

**Comment by ponceta** [comment]
@m-kuhn could you please have a look?

**Comment by m-kuhn** [comment]
This (unreleased) action depended on unreleased code. Done now with qgepplugin release 1.1.10.

**Comment by ponceta** [comment]
Thanks! It works fine on qgepplugin 1.1.10 indeed!
